post https://server-proffy.marconwillian.dev/connections HTTP/1.1
Authorization: Basic user:passwd
Content-Type: application/json

{
    "user_id": 1
}


###

get https://server-proffy.marconwillian.dev/connections HTTP/1.1


###

get https://server-ecoleta.marconwillian.dev/items HTTP/1.1